# Generated by Django 5.0 on 2023-12-14 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='tf',
            field=models.BooleanField(default=False, verbose_name='чекбокс'),
        ),
    ]
