# Generated by Django 5.0 on 2023-12-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_tf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='tf',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
